// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcApiInputTypes = { proc_name: "poll_state"; input_type: null } | { proc_name: "upload"; input_type: { __taurpc_type: string } }

export type ParserState = "None" | { Processing: number } | "Processed"

export type TauRpcApiOutputTypes = { proc_name: "poll_state"; output_type: ParserState } | { proc_name: "upload"; output_type: null }

const ARGS_MAP = {"":"{\"upload\":[\"path\"],\"poll_state\":[]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
}